# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: ModifyFile
    displayName: 'Modify all changed .js files'
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
      - script: |
          set -e
          # Get all modified .js files in the current commit/PR
          MODIFIED_FILES=$(git diff --name-only origin/main...HEAD | grep '\.js$')
          echo "Modified JS files: $MODIFIED_FILES"
          for file in $MODIFIED_FILES; do
            echo "Processing $file"
            node $(Build.SourcesDirectory)/pipelines/scripts/file-content-modifier.js "$(Build.SourcesDirectory)/$file"
          done
        displayName: "Send contents of all modified .js files to endpoint and update files"
